# Yelp Restaurant Data Mining Project

## Dataset Understanding

This notebook explores the Yelp restaurant dataset and provides an initial understanding of the data structure, variables, and basic statistics before any preprocessing or modelling activities are performed.

Initially importing all the libraries

In [1]:
import sys
print(sys.version)

3.12.10 (v3.12.10:0cc81280367, Apr  8 2025, 08:46:59) [Clang 13.0.0 (clang-1300.0.29.30)]

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("All libraries loaded successfully")

All libraries loaded successfully

## Load Dataset

Load the Yelp restaurant dataset into a Pandas DataFrame.

In [ ]:
#Load dataset
df = pd.read_csv("cleaned_yelp_restaurants.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (34987, 8)

,business_id,name,city,state,stars,review_count,categories,WiFi_Status
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",u'free'
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,Ashland City,TN,2.0,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...",u'no'
2,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,Nashville,TN,1.5,10,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...",u'no'
3,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,Tampa Bay,FL,4.0,10,"Vietnamese, Food, Restaurants, Food Trucks",No Info
4,il_Ro8jwPlHresjw9EGmBg,Denny's,Indianapolis,IN,2.5,28,"American (Traditional), Restaurants, Diners, B...",u'no'

## Dataset Information

Examine the data types and structure of the dataset.

In [5]:
# Display dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34987 entries, 0 to 34986
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   34987 non-null  str
 1   name          34987 non-null  str
 2   city          34987 non-null  str
 3   state         34987 non-null  str
 4   stars         34987 non-null  float64
 5   review_count  34987 non-null  int64
 6   categories    34987 non-null  str
 7   WiFi_Status   34962 non-null  str
dtypes: float64(1), int64(1), str(6)
memory usage: 2.1 MB

## Descriptive Statistics

Generate summary statistics for numerical attributes.

In [6]:
# Summary statistics

df.describe()

              stars  review_count
count  34987.000000  34987.000000
mean       3.523895    104.142767
std        0.862661    220.590683
min        1.000000      5.000000
25%        3.000000     16.000000
50%        3.500000     40.000000
75%        4.000000    109.000000
max        5.000000   7568.000000

## Unique Values

Determine the number of unique values in each column.

In [7]:
# Count unique values

df.nunique()

business_id     34987
name            23444
city              846
state              16
stars               9
review_count     1107
categories      22304
WiFi_Status         7
dtype: int64